-- ═══════════════════════════════════════════════════════════════════════════
-- BOOMTCHAK V3 — Seed du pool école (SQL)
-- À coller dans Supabase > SQL Editor > New query > Run
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Familles ─────────────────────────────────────────────────────────────────
insert into familles (id, nom, scope) values
  ('fam_base',       'Référentiel', 'school'),
  ('fam_euclidien',  'Euclidien',   'school'),
  ('fam_afrocubain', 'Afro-cubain', 'school'),
  ('fam_africain',   'Africain',    'school'),
  ('fam_bresilien',  'Brésilien',   'school'),
  ('fam_caraibe',    'Caraïbe',     'school'),
  ('fam_flamenco',   'Flamenco',    'school')
on conflict (id) do update set nom = excluded.nom, scope = 'school';

-- ── Patterns ─────────────────────────────────────────────────────────────────
insert into patterns (id, nom, sequence, pas, familles_ids, encyclo_ref, scope, approved) values
  ('pulse1',  'Pulse',                  'X',                   1,  array['fam_base'],                               null,       'school', true),
  ('bin2',    'Bin (1:2)',               'X.',                  2,  array['fam_base'],                               null,       'school', true),
  ('ter3',    'Ter (1:3)',               'X..',                 3,  array['fam_base'],                               null,       'school', true),
  ('fl4',     'Four on the Floor (2,4)', 'X.X.X.X.',            8,  array['fam_base'],                               'fl4',      'school', true),
  ('offbeat', 'Off Beat (2,4)',           '.X.X.X.X',            8,  array['fam_base'],                               'offbeat',  'school', true),
  ('pulse4',  'Pulse (4:4)',             'XXXX',                4,  array['fam_base'],                               null,       'school', true),
  ('sync4',   'Double Up (2:4)',         '..XX',                4,  array['fam_base'],                               null,       'school', true),
  ('silence', 'Silence',                 '....',                4,  array['fam_base'],                               null,       'school', true),
  ('tres',    'Tresillo',                'X..X..X.',            8,  array['fam_euclidien','fam_afrocubain'],          'tres',     'school', true),
  ('cinq',    'Cinquillo',               'X.XX.XX.',            8,  array['fam_afrocubain'],                         'cinq',     'school', true),
  ('hab',     'Habanera',                'X..XX.X.',            8,  array['fam_afrocubain'],                         'hab',      'school', true),
  ('afoxe',   E'Afox\u00ea / Bolero',   'X..X.X..',            8,  array['fam_afrocubain','fam_africain'],           'afoxe',    'school', true),
  ('reggae',  'Clave Reggae',            '....X.X.',            8,  array['fam_caraibe'],                            'reggae',   'school', true),
  ('son32',   'Son 3:2',                 'X..X..X...X.X...',   16,  array['fam_afrocubain'],                         'son32',    'school', true),
  ('son',     'Son (2:3)',               '..X.X...X..X..X.',   16,  array['fam_afrocubain'],                         'son',      'school', true),
  ('rum32',   'Rumba 3:2',               'X..X...X..X.X...',   16,  array['fam_afrocubain'],                         'rum32',    'school', true),
  ('shiko',   'Shiko',                   'X...X.X...X.X...',   16,  array['fam_africain'],                           'shiko',    'school', true),
  ('bossa',   'Bossa Nova',              'X..X..X...X..X..',   16,  array['fam_bresilien'],                          'bossa',    'school', true),
  ('gahu',    'Gahu',                    'X..X..X...X...X.',   16,  array['fam_africain'],                           'gahu',     'school', true),
  ('souk',    'Soukous',                 'X..X..X...XX....',   16,  array['fam_africain'],                           'souk',     'school', true),
  ('samba',   'Samba',                   'X..X.X.X..X.X.X.',   16,  array['fam_bresilien'],                          'samba',    'school', true),
  ('cascara', 'Cascara 3:2',             'X.XX.X.XX.X.XX.X',   16,  array['fam_afrocubain'],                         'cascara',  'school', true),
  ('tumbao',  'Tumbao',                  'X.XX.X.X.X.X.X.X',   16,  array['fam_afrocubain'],                         'tumbao',   'school', true),
  ('fume',    'Fume-fume',               'X.X.X..X.X..',       12,  array['fam_africain'],                           'fume',     'school', true),
  ('bembe',   E'Bemb\u00e9',             'X.X.XX.X.X.X',       12,  array['fam_africain'],                           'bembe',    'school', true),
  ('solea',   E'Sol\u00e9\u00e0',        '..X..X.X.X.X',       12,  array['fam_flamenco'],                           'solea',    'school', true)
on conflict (id) do update set
  nom = excluded.nom, sequence = excluded.sequence, familles_ids = excluded.familles_ids,
  encyclo_ref = excluded.encyclo_ref, scope = 'school', approved = true;

-- Patterns Empty (templates vides, 1 par taille de pas)
-- empty_4 omis : couvert par 'silence' (meme sequence, meme famille)
insert into patterns (id, nom, sequence, pas, familles_ids, encyclo_ref, scope, approved) values
  ('empty_1',  'Empty 1',  '.',                1,  array['fam_base'], null, 'school', true),
  ('empty_2',  'Empty 2',  '..',               2,  array['fam_base'], null, 'school', true),
  ('empty_3',  'Empty 3',  '...',              3,  array['fam_base'], null, 'school', true),
  ('empty_5',  'Empty 5',  '.....',            5,  array['fam_base'], null, 'school', true),
  ('empty_6',  'Empty 6',  '......',           6,  array['fam_base'], null, 'school', true),
  ('empty_7',  'Empty 7',  '.......',          7,  array['fam_base'], null, 'school', true),
  ('empty_8',  'Empty 8',  '........',         8,  array['fam_base'], null, 'school', true),
  ('empty_9',  'Empty 9',  '.........',        9,  array['fam_base'], null, 'school', true),
  ('empty_10', 'Empty 10', '..........',       10,  array['fam_base'], null, 'school', true),
  ('empty_11', 'Empty 11', '...........',      11,  array['fam_base'], null, 'school', true),
  ('empty_12', 'Empty 12', '............',     12,  array['fam_base'], null, 'school', true),
  ('empty_13', 'Empty 13', '.............',    13,  array['fam_base'], null, 'school', true),
  ('empty_14', 'Empty 14', '..............',   14,  array['fam_base'], null, 'school', true),
  ('empty_15', 'Empty 15', '...............',  15,  array['fam_base'], null, 'school', true),
  ('empty_16', 'Empty 16', '................', 16,  array['fam_base'], null, 'school', true)
on conflict (id) do update set
  nom = excluded.nom, sequence = excluded.sequence, familles_ids = excluded.familles_ids,
  scope = 'school', approved = true;

-- ── Grooves ──────────────────────────────────────────────────────────────────
insert into grooves (id, nom, familles_ids, band_defaut, tempo_min, tempo_max, tempo_defaut, signature, layers, scope, approved) values
  ('salsa32',   'Salsa 3:2',  array['fam_afrocubain'], 'band_perc',    80,  360, 200, '4/4',
   '[{"id":"grave","patternId":"tres",    "mute":false,"shift":0,"halfOn":false,"doubleOn":true },{"id":"aigu", "patternId":"son32",   "mute":false,"shift":0,"halfOn":false,"doubleOn":true },{"id":"noise","patternId":"cascara","mute":false,"shift":0,"halfOn":false,"doubleOn":true }]',
   'school', true),
  ('bossanova', 'Bossa Nova', array['fam_bresilien'],   'band_minimal', 60,  200, 160, '4/4',
   '[{"id":"grave","patternId":"sync4",  "mute":false,"shift":1,"halfOn":false,"doubleOn":false},{"id":"aigu", "patternId":"bossa",   "mute":false,"shift":0,"halfOn":false,"doubleOn":false},{"id":"noise","patternId":"sync4",  "mute":false,"shift":0,"halfOn":false,"doubleOn":false}]',
   'school', true),
  ('techno',    'Techno',     array[]::text[],          'band_electro', 80,  400, 260, '4/4',
   '[{"id":"grave","patternId":"fl4",    "mute":false,"shift":0,"halfOn":false,"doubleOn":false},{"id":"aigu", "patternId":"tres",    "mute":true, "shift":0,"halfOn":false,"doubleOn":true },{"id":"noise","patternId":"offbeat","mute":false,"shift":0,"halfOn":false,"doubleOn":false}]',
   'school', true),
  ('reggae',    'Reggae',     array['fam_caraibe'],     'band_rock',    60,  220, 200, '4/4',
   '[{"id":"grave","patternId":"reggae", "mute":false,"shift":0,"halfOn":false,"doubleOn":false},{"id":"aigu", "patternId":"offbeat", "mute":false,"shift":0,"halfOn":true, "doubleOn":false},{"id":"noise","patternId":"sync4",  "mute":false,"shift":0,"halfOn":false,"doubleOn":false}]',
   'school', true),
  ('dancehall', 'Dancehall',  array['fam_caraibe'],     'band_perc',    80,  320, 200, '4/4',
   '[{"id":"grave","patternId":"tres",   "mute":false,"shift":0,"halfOn":false,"doubleOn":true },{"id":"aigu", "patternId":"offbeat", "mute":false,"shift":0,"halfOn":true, "doubleOn":true },{"id":"noise","patternId":"hab",     "mute":false,"shift":0,"halfOn":false,"doubleOn":true }]',
   'school', true)
on conflict (id) do update set
  nom = excluded.nom, familles_ids = excluded.familles_ids, layers = excluded.layers,
  signature = excluded.signature, scope = 'school', approved = true;


-- ── Encyclopédie ─────────────────────────────────────────────────────────────
insert into encyclo (key, chapo, bullets, scope, approved) values
('fl4',
 $$Le "Four on the Floor" est le rythme fondateur des musiques de danse électronique — une frappe sur chaque temps binaire (les temps 2 et 4 d'une mesure à 4/4, soit toutes les croches paires sur 8 pas). Sa régularité absolue ancre physiquement l'auditeur et synchronise les corps en masse. Il est indissociable de son complémentaire exact, l'Off Beat, qui frappe exactement là où lui se tait — ensemble ils forment le métronome binaire du dancefloor.$$,
 $$[["Origine","Disco américain, années 70 — DJ Frankie Knuckles, Larry Levan à New York et Chicago ; popularisé en Europe par la scène house puis techno des années 80-90."],["Écriture","X.X.X.X.\nFrappe sur chaque temps binaire (croches 1,3,5,7)\n4 frappes sur 8 pas"],["Utilisation","Techno, house, EDM, disco ; base universelle des musiques de dancefloor depuis 50 ans."],["Sensation","Ancrage total, prévisibilité rassurante, énergie par accumulation et non par tension."],["Relations","Complémentaire exact de l'Off Beat (2,4) : là où l'un frappe, l'autre se tait — les superposer produit le Pulse (4:4) continu."]]$$::jsonb,
 'school', true),
('offbeat',
 $$L'Off Beat est le complémentaire exact du Four on the Floor — il frappe précisément sur les contretemps, là où son partenaire se tait. Ensemble ils forment le métronome binaire fondamental du dancefloor disco et électronique. L'Off Beat seul crée cette sensation de suspension et de rebond caractéristique du groove de danse — le corps anticipe la frappe suivante en s'appuyant sur l'absence.$$,
 $$[["Origine","Disco américain, années 70 — même héritage que le Four on the Floor ; le skank reggae et le upstroke funk sont des ancêtres directs."],["Écriture",".X.X.X.X\nFrappe sur chaque contretemps (croches 2,4,6,8)\n4 frappes sur 8 pas — complémentaire exact du Four on the Floor"],["Logique","Four on the Floor + Off Beat = Pulse (4:4) — deux rythmes opposés dont l'union forme la pulsation continue."],["Sensation","Suspension, rebond, légèreté — le groove est porté par l'anticipation plutôt que par l'appui."],["Utilisation","Guitare rythmique funk et disco (le \"chicken scratch\") ; piano ou orgue en house ; hi-hat ouvert en techno ; clap ou snare en pop."]]$$::jsonb,
 'school', true),
('tres',
 $$Le Tresillo est probablement le pattern rythmique le plus répandu dans les musiques populaires mondiales — trois frappes sur 8 pas, distribution euclidienne maximale. On le retrouve dans quasiment toutes les musiques issues de la diaspora africaine aux Amériques et au-delà, souvent sans qu'il soit nommé. Sa simplicité apparente cache une tension rythmique réelle avec la pulsation binaire.$$,
 $$[["Origine","Terme cubain, mais le pattern est pan-africain et pan-américain ; présent dans les Caraïbes, le Brésil, la Nouvelle-Orléans."],["Écriture","X..X..X.\nIntervalles : 3-3-2\nE(3,8) — distribution euclidienne maximale sur 8 pas"],["Logique","Le 1er coup lance le rythme ; le 2e coup (\"bombo\", au pas 4) crée l'élan ; le 3e coup (\"ponche\", au pas 7) résout — c'est l'asymétrie finale (intervalle 2 au lieu de 3) qui génère la tension caractéristique."],["Utilisation","Blues, jazz, cumbia, son cubain ; la main gauche du piano de Hound Dog d'Elvis ; de nombreuses lignes de basse hip-hop."],["Relations","Sous-composant de Son 3:2 (les 3 premières frappes) ; présent dans Cinquillo, Habanera et Rumba par déformation ou extension."]]$$::jsonb,
 'school', true),
('cinq',
 $$Le Cinquillo est l'un des rythmes fondateurs de la musique afro-cubaine, né de l'extension et de la densification du Tresillo. Cinq frappes sur 8 pas, il remplit l'espace laissé libre par son ancêtre en intercalant deux frappes supplémentaires. Présent dans la contradanza du XIXe siècle, il a traversé le danzón, le mambo et le cha-cha-chá, devenant un composant-clé de la généalogie rythmique cubaine.$$,
 $$[["Origine","Cuba, XIXe siècle ; contradanza afro-cubaine, ancêtre direct du danzón et du mambo."],["Écriture","X.XX.XX.\nIntervalles : 2-1-2-1-2\n5 frappes sur 8 pas"],["Logique","C'est le Tresillo avec des coups ajoutés juste avant le bombo (pas 3) et le ponche (pas 6) — même squelette, densité presque doublée."],["Sensation","Plus nerveux et syncopé que le Tresillo, sentiment d'urgence et de rebond continu."],["Relations","Extension directe du Tresillo ; intermédiaire entre Tresillo (3 frappes) et Pulse (5 frappes continues sur 8)."]]$$::jsonb,
 'school', true),
('hab',
 $$La Habanera est un rythme né à La Havane au début du XIXe siècle, issu du contradanse européen métissé de rythmes africains. Elle a voyagé vers l'Espagne et l'Amérique latine avec une facilité remarquable, devenant l'un des premiers rythmes de la diaspora afro-cubaine à pénétrer la musique savante européenne.$$,
 $$[["Origine","La Havane, début XIXe ; importée en Espagne où elle influence le flamenco et la zarzuela ; Bizet l'utilise dans Carmen (1875)."],["Écriture","X..XX.X.\nIntervalles : 3-1-2-2\nTresillo + contretemps au pas 4"],["Sensation","Balancement asymétrique, légèreté malgré la syncope, caractère dansé et élégant."],["Utilisation","Tango argentin (qui en descend directement), bolero cubain, blues américain (Hey Bo Diddley) ; Carmen de Bizet (1875) popularise la Habanera en Europe savante."],["Anecdote","Bo Diddley a construit toute sa carrière sur ce pattern — appelé \"Bo Diddley beat\" en Amérique du Nord, sans que personne ne sache toujours qu'il vient de La Havane."]]$$::jsonb,
 'school', true),
('afoxe',
 $$L'Afoxê (ou Ijexá) est un rythme afro-brésilien de Salvador de Bahia, issu de la tradition yoruba-nagô du candomblé. Distinct de la Samba, il appartient à une famille rythmique plus proche des racines africaines — les mêmes qui ont engendré le Bembé à Cuba. Sa douceur hypnotique contraste avec la puissance explosive de la Samba.$$,
 $$[["Origine","Salvador de Bahia (Brésil) ; tradition yoruba-nagô du candomblé ; l'Afoxê Filhos de Gandhi (fondé en 1949) est le groupe le plus célèbre."],["Écriture","X..X.X..\nIntervalles : 3-2-3\n3 frappes sur 8 pas"],["Sensation","Douceur hypnotique, balancement lent et profond, sentiment de procession."],["Utilisation","Carnaval de Salvador, candomblé ; Gilberto Gil et Caetano Veloso l'ont popularisé internationalement dans les années 70-80."],["Relations","Même nombre de frappes que le Tresillo (3 sur 8) mais distribution différente (3-2-3 vs 3-3-2) — comparer les deux révèle comment un même nombre de frappes peut produire des caractères radicalement différents."]]$$::jsonb,
 'school', true),
('reggae',
 $$La Clave Reggae est le pattern fondateur de la rythmique jamaïcaine — deux frappes sur 8 pas, placées sur le contretemps du 3e temps et son "et". Sa caractéristique la plus frappante est l'absence totale de frappe sur les 4 premiers pas — ce silence initial est précisément ce qui crée la sensation de "retard" caractéristique du reggae, ce groove pesant et suspendu qui a influencé la quasi-totalité de la musique populaire mondiale.$$,
 $$[["Origine","Jamaïque — racine profonde dans le mento, musique folk jamaïcaine du XIXe siècle. Le skank et l'appui profond sur le 3e temps sans frapper le 1er sont les signatures sonores du reggae."],["Écriture","....X.X.\nIntervalles : 4-2-2\n2 frappes sur 8 pas — vide des 4 premiers pas constitutif"],["Logique","Grosse caisse sur le 3e temps (pas 5) et son contretemps (pas 7) — inversion complète du 4 on the floor."],["Sensation","Pesanteur, suspension, sentiment d'être \"derrière\" la pulsation — le groove le plus \"late\" du dictionnaire."],["Utilisation","Reggae roots, dub — Bob Marley, Lee Scratch Perry, King Tubby ; absorbé par le hip-hop, le trip-hop (Massive Attack, Portishead)."]]$$::jsonb,
 'school', true),
('son32',
 $$Le Son clave est le squelette rythmique de toute la musique afro-cubaine — né de la rencontre entre rythmes bantous et guitare espagnole dans l'Oriente cubain au XIXe siècle. Joué aux claves, deux bâtons de bois dur, il structure une famille musicale entière qui a rayonné mondialement. Son asymétrie fondamentale — 5 frappes inégalement réparties sur 16 pas — est précisément ce qui génère le groove syncopé caractéristique de la salsa.$$,
 $$[["Origine","Cuba, XIXe siècle, confluence yoruba/bantou et espagnole ; \"clave\" désigne à la fois l'instrument et la fonction structurelle (\"clé\" en espagnol)."],["Écriture","X..X..X...X.X...\nIntervalles : 3-3-4-2-4\nE(5,16)"],["Logique","La partie \"3\" (3 frappes) crée l'élan, la partie \"2\" (2 frappes) pose la résolution — l'asymétrie génère une tension permanente avec la pulsation."],["Sensation","Groove tiré en avant, sentiment d'incomplétude qui appelle la résolution, quasi-impossible de rester immobile."],["Anecdote","Dans la tradition cubaine, \"jouer contre la clave\" est la faute musicale suprême — un orchestre entier peut s'arrêter pour corriger."]]$$::jsonb,
 'school', true),
('son',
 $$Le Son 2:3 est la rotation du Son clave 3:2 — les mêmes 5 frappes décalées de 8 pas, ce qui inverse la logique élan/résolution. Ce n'est pas un rythme séparé mais une position différente du même pattern dans le cycle. Dans la pratique cubaine, les deux formes coexistent et dialoguent au sein d'un même morceau.$$,
 $$[["Écriture","..X.X...X..X..X.\nRotation du Son 3:2 (décalage 8 pas)\nRésolution en premier"],["Sensation","Plus posé que le 3:2, sentiment d'être \"derrière le temps\", légère flottaison."],["Usage","Certains instruments jouent en 2:3 pendant que d'autres tiennent le 3:2 — c'est cette superposition qui crée la richesse de la clave."],["Relations","Même pattern que Son 3:2, décalage de 8 pas — comprendre les deux ensemble est essentiel pour saisir la logique de la clave."]]$$::jsonb,
 'school', true),
('rum32',
 $$La Rumba clave est la cousine "africaine" du Son — plus proche des racines yoruba et bantou, moins métissée avec l'harmonie européenne. Elle diffère du Son par le déplacement d'une seule frappe (la 3e, avancée d'un pas), ce qui la fait sonner plus "derrière le temps" et plus funky. C'est le rythme de la rumba cubaine traditionnelle (yambu, guaguancó, columbia).$$,
 $$[["Origine","Cuba, communautés afro-cubaines du XIXe siècle ; la rumba est une forme populaire urbaine, pas un rythme de cérémonie."],["Écriture","X..X...X..X.X...\nIntervalles : 3-4-3-2-4\n3e frappe du Son 3:2 avancée d'un pas"],["Sensation","Plus \"derrière le temps\" que le Son, groove plus lourd, sentiment de retenue puis de lâcher."],["Relations","Variante du Son 3:2 par déplacement d'une seule frappe — même nombre de pas, même nombre de frappes, caractère sensiblement différent."]]$$::jsonb,
 'school', true),
('shiko',
 $$Le Shiko est un des rythmes fondamentaux de l'Afrique de l'Ouest, issu des peuples Ewe du Ghana et du Togo. Sa structure euclidienne — 5 frappes sur 16 pas — le place dans la même famille mathématique que le Son cubain, mais son caractère est radicalement différent : plus circulaire, moins tendu, plus hypnotique.$$,
 $$[["Origine","Ewe (Ghana/Togo) ; joué aux tambours dans les cérémonies communautaires."],["Écriture","X...X.X...X.X...\nIntervalles : 4-2-4-2-4\nE(5,16)"],["Logique","Alternance régulière 4-2 créant un balancement en deux temps inégaux — plus régulier que la clave, moins de tension élan/résolution."],["Sensation","Groove circulaire et hypnotique, sensation de rotation continue, moins \"tiré en avant\" que la clave."],["Relations","Même E(5,16) que Son 3:2, Bossa Nova et Gahu — trois façons différentes de placer 5 frappes sur 16 pas."]]$$::jsonb,
 'school', true),
('souk',
 $$Le Soukous est le rythme de la rumba congolaise, né à Kinshasa et Brazzaville dans les années 40-60 de la fusion entre la rumba cubaine importée par des disques, les rythmes bantous et la guitare électrique. Il est l'exemple parfait d'un aller-retour culturel : la rumba afro-cubaine revient en Afrique centrale et y génère une nouvelle forme musicale autonome.$$,
 $$[["Origine","Congo-Kinshasa et Congo-Brazzaville, années 50-60 ; Franco Luambo et l'OK Jazz, Tabu Ley Rochereau ; \"soukous\" vient du français \"secouer\"."],["Écriture","X..X..X...XX....\nVariante du Son 3:2\nCondensation des deux dernières frappes"],["Sensation","Groove léger et dansant, en avant du temps, accroche immédiate."],["Relations","Retour du rythme bantou en Afrique via Cuba — un des exemples les plus frappants de \"boucle culturelle\" dans l'histoire de la musique populaire."]]$$::jsonb,
 'school', true),
('bossa',
 $$La Bossa Nova est née à Rio de Janeiro en 1958 de la rencontre entre la samba brésilienne, le cool jazz américain et une nouvelle génération de musiciens cariocas. João Gilberto, en tapant ce pattern à la guitare tout en chantant et jouant les accords, a créé une texture entièrement nouvelle.$$,
 $$[["Origine","Rio de Janeiro, 1958 ; João Gilberto, Tom Jobim, Vinicius de Moraes — Chega de Saudade est le premier enregistrement."],["Écriture","X..X..X...X..X..\nIntervalles : 3-3-4-3-3\nE(5,16) — seule forme quasi-symétrique de la famille"],["Singularité","Seul rythme de la famille E(5,16) avec une quasi-symétrie. La sensation de flottaison vient du fait que tous les coups sauf le premier tombent en contretemps."],["Sensation","Légèreté, swing sans lourdeur, sentiment de suspension perpétuelle — le temps semble glisser plutôt que marcher."],["Relations","Même E(5,16) que Son 3:2, Shiko, Gahu — famille commune, caractère radicalement différent."]]$$::jsonb,
 'school', true),
('gahu',
 $$Le Gahu est un rythme de danse des Ewe du Ghana, apparu dans les années 40 et intégrant des influences extérieures. C'est l'un des rythmes africains les plus étudiés par les ethnomusicologues occidentaux, notamment par John Miller Chernoff dans African Rhythm and African Sensibility (1979).$$,
 $$[["Origine","Ewe du Ghana, milieu XXe siècle ; danse communautaire mixte."],["Écriture","X..X..X...X...X.\nIntervalles : 3-3-4-4-2\nE(5,16) — vide central caractéristique"],["Logique","Le grand intervalle central de 4+4 crée un \"vide\" inhabituel au milieu du pattern — c'est lui qui donne au Gahu son caractère suspendu."],["Sensation","Groove aéré, suspension au milieu du cycle, résolution rapide en fin de pattern."],["Relations","Troisième membre de la famille E(5,16) avec Son 3:2 et Shiko ; le vide central le distingue nettement des deux autres."]]$$::jsonb,
 'school', true),
('samba',
 $$La Samba est le rythme national brésilien, né à Rio de Janeiro au début du XXe siècle dans les communautés afro-brésiliennes. Sa structure sur 16 pas est plus dense que la Bossa Nova qui en dérive, avec 7 frappes créant un enchevêtrement caractéristique.$$,
 $$[["Origine","Rio de Janeiro, début XXe siècle ; communautés bahianaises installées dans les favelas ; institutionnalisé par le Carnaval."],["Écriture","X..X.X.X..X.X.X.\nIntervalles : 3-2-2-3-2-2-2\nE(7,16) — structure quasi-palindromique"],["Logique","Ce dialogue constant entre temps et contretemps crée une tension permanente qui appelle le corps à se mouvoir."],["Sensation","Énergie explosive et en avant du temps. Le groove est physiquement irrésistible."],["Relations","Même densité que Bembé (7 frappes) mais sur 16 pas — sensation très différente, moins oppressante."]]$$::jsonb,
 'school', true),
('fume',
 $$Le Fume-fume est un des rythmes fondateurs de la musique Ewe du Ghana, utilisé comme rythme-référence ("bell pattern") dans les cérémonies collectives. Sur base 12, il répartit 6 frappes en deux groupes asymétriques. C'est l'un des rythmes les plus analysés dans l'ethnomusicologie africaine.$$,
 $$[["Origine","Ewe (Ghana/Togo) ; joué à la cloche (gankogui) pour organiser les autres instruments de l'ensemble."],["Écriture","X.X.X..X.X..\nIntervalles : 2-2-3-2-3\nE(6,12)"],["Singularité","Peut être entendu en 3 (deux groupes de 6) ou en 2 (trois groupes de 4) — rythme \"ambigu\" jouant sur la frontière binaire/ternaire."],["Sensation","Oscillation, ambiguïté métrique, sensation de \"toupie\" pouvant basculer d'un côté ou de l'autre."],["Relations","Complémentaire exact de Bembé — les 6 pas de l'un sont les 6 silences de l'autre."]]$$::jsonb,
 'school', true),
('cascara',
 $$La Cáscara 3:2 ("coquille" en espagnol) est le pattern rythmique joué sur la coque métallique des timbales dans la salsa et la musique afro-cubaine. Dense, continue, asymétrique, elle est à la salsa ce que le charley est au jazz : l'horloge interne qui fait swinguer le tout.$$,
 $$[["Origine","Cuba, ensembles de salsa et de son des années 40-60 ; jouée sur les timbales par le timbalero."],["Écriture","X.XX.X.XX.X.XX.X\nIntervalles : 2-1-2-2-1-2-2-1-2-1\n10 frappes sur 16 pas"],["Logique","Elle contient toutes les frappes de la clave Son 3:2 plus des frappes supplémentaires — la clave enrichie d'un contrechant constant."],["Sensation","Dense et régulière en surface, elle crée un tapis rythmique continu sur lequel les autres instruments brodent."],["Utilisation","Timbales en salsa (sections verses, piano solos) ; Tito Puente, Willie Colón."]]$$::jsonb,
 'school', true),
('tumbao',
 $$Le Tumbao est le pattern de piano (ou tres) fondamental de la musique cubaine — ce que les Nord-Américains appellent montuno. Né dans le son montuno avec Arsenio Rodríguez, il est devenu le langage universel du piano en salsa, mambo et timba.$$,
 $$[["Origine","Cuba, son montuno, années 30-40 ; Arsenio Rodríguez introduit le piano dans le conjunto cubain."],["Écriture","X.XX.X.X.X.X.X.X\nPattern de piano (guajeo/montuno)\nPresque tous les coups sont en contretemps"],["Logique","Le pianiste joue des accords syncopés en arpèges, anticipant la pulsation. Le pattern s'organise strictement par rapport à la clave."],["Sensation","Tapis harmonique hypnotique, propulsion, sentiment que les accords \"flottent\" au-dessus du tempo."],["Relations","Distinct du tumbao de basse (pattern de contrebasse) avec lequel il s'interloque — les deux ensemble définissent le groove afro-cubain."]]$$::jsonb,
 'school', true),
('solea',
 $$La Soleá est la mère du flamenco — le palo (style) le plus fondamental, celui par lequel commence traditionnellement l'apprentissage de la guitare flamenca. Son compás (rythme) de 12 temps avec des accents sur les temps 3, 6, 8, 10 et 12 est une structure unique au monde, à la frontière du binaire et du ternaire.$$,
 $$[["Origine","Andalousie (Espagne), probablement Séville et Cadix, XVIIIe-XIXe siècle ; transmission orale dans les communautés gitanes."],["Écriture","..X..X.X.X.X\nAccents sur les temps 3-6-8-10-12\n5 frappes sur 12 pas — structure 3+3+2+2+2"],["Logique","Le compás commence sur un silence (temps 1 muet, caractéristique du flamenco) — arc dramatique tension/résolution en un seul cycle."],["Singularité","L'amalgame binaire/ternaire (6/8 + 3/4) crée une ambiguïté métrique qui est précisément la source de l'expressivité flamenco."],["Sensation","Gravité, lenteur intérieure, dignité — la Soleá est le temple du duende flamenco ; elle ne se précipite jamais."]]$$::jsonb,
 'school', true),
('bembe',
 $$Le Bembé est un rythme de cérémonie yoruba, joué dans la Santería cubaine pour l'invocation des Orishas. C'est le rythme euclidien le plus dense du dictionnaire sur base 12 — 7 frappes sur 12 pas, laissant à peine de l'espace. Cette densité quasi-continue produit une tension hypnotique sans repos qui explique son usage rituel.$$,
 $$[["Origine","Yoruba (Nigeria/Bénin), transplanté à Cuba avec la traite ; \"Bembé\" désigne aussi la cérémonie elle-même."],["Utilisation","Rituels de Santería (Cuba) ; jazz modal : Miles Davis Kind of Blue (1959), Coltrane Africa/Brass (1961) ; Steve Reich, Drumming (1971)."],["Écriture","X.X.XX.X.X.X\nIntervalles : 2-2-1-2-2-2\nE(7,12) — maximum euclidien sur base 12"],["Singularité","Un seul intervalle d'1 pas (entre frappes 5 et 6) — micro-accentuation caractéristique, comme un trébuchement contrôlé."],["Sensation","Urgence hypnotique, absence de respiration, état de transe — la densité est fonctionnelle, pas décorative."]]$$::jsonb,
 'school', true),
('poumtchak',
 $$BoomTchak permet de découvrir les rythmes fondamentaux qui constituent le langage rythmique mondial : des grooves africains aux musiques électroniques, en passant par les Caraïbes et le Brésil… L'objectif est de comprendre comment des structures simples génèrent une richesse infinie. Cette appli permet d'écouter, voir, comprendre, jouer ou composer des rythmiques.$$,
 $$[["Groove","Un groove = une superposition de patterns qui forment une rythmique cohérente. Chaque ligne est une couche."],["Pattern","Une cellule rythmique qui se répète en boucle. Chaque pattern a un rôle : ancrer le temps, créer la tension, marquer le contretemps…"],["Sons & instruments","Trois couches complémentaires : Grave (kick, basse), Aigu (snare, clave), Noise (hi-hat, shaker). Son paramétrable en hauteur et volume."],["Notation","X = fort, x = faible, . = silence. Vue ⊞ linéaire ou ◎ circulaire pour voir les patterns et leurs symétries."],["Tempo","Réglage en SPM (Steps Par Minute). /2 et ×2 divisent ou doublent toutes les couches en restant synchronisés."],["Usage","TX = mode enseignant (édition complète), SX = mode élève (exploration et édition de ses propres patterns)."]]$$::jsonb,
 'school', true),
('misc_groove',
 $$Un groove est une superposition de patterns qui forment ensemble une rythmique cohérente. Dans une section rythmique, chacun joue une cellule répétitive, et c'est leur empilement qui crée le groove. Dans BoomTchak, chaque ligne du groove est appelée une couche et joue un pattern.$$,
 $$[]$$::jsonb,
 'school', true),
('misc_pattern',
 $$Un pattern est une cellule rythmique : une séquence de sons et de silences qui se répète en boucle. Chaque pattern a un rôle fonctionnel dans l'ensemble : ancrer le temps, créer la tension, marquer le contretemps, compléter une autre couche… La combinaison de rôles différents est ce qui fait swinguer un groove.$$,
 $$[]$$::jsonb,
 'school', true),
('misc_sons',
 $$Chaque couche joue un son paramétrable via le bouton Sons ▶. BoomTchak propose trois couches aux fonctions complémentaires : Grave (kick, basse, tambour), Aigu (snare, guitare, clave), Noise (hi-hat, pulsation, shaker). Chaque son peut être réglé en hauteur, timbre et volume.$$,
 $$[]$$::jsonb,
 'school', true),
('misc_notations',
 $$Chaque pattern est représenté comme une grille de cases — un chemin pour la musique. Chaque case est un step, l'unité de temps de base (1 step = 1 croche). BoomTchak propose deux vues : ⊞ linéaire (grille gauche→droite) et ◎ circulaire (rotation horaire depuis 12h).$$,
 $$[["X — son fort","Volume plein (100%). Le pas est joué avec toute son intensité."],["x — son faible","Volume réduit (33%). Le squelette rythmique est maintenu, la dynamique allégée."],["· — silence","Pas joué. L'absence de son est constitutive du pattern au même titre que les frappes."]]$$::jsonb,
 'school', true),
('misc_tempo',
 $$Le tempo règle la vitesse globale du groove, exprimé en BPM (battements par minute). Le slider et le bouton Tap permettent d'ajuster le tempo en temps réel. La valeur s'affiche aussi en notation musicale (♩ noire, ♩. noire pointée, 𝅗𝅥 blanche) selon la signature courante.$$,
 $$[["BPM","Battements par minute — 1 BPM correspond à 1 temps (noire en 4/4). Repères : 60 = lent, 120 = marche, 200 = très rapide."],["Tap Tempo","Frapper plusieurs fois la zone Tap en suivant le pulse permet d'indiquer le tempo à l'oreille, sans chercher la valeur numérique."],["×2 / /2 globaux","Doublent ou divisent le tempo de toutes les couches simultanément, en restant synchronisés."],["Vitesse par couche","Chaque couche peut avoir sa propre vitesse relative indépendante via les boutons /2, ×2 et T du volet Mod — voir article Transformations."]]$$::jsonb,
 'school', true),
('misc_transformations',
 $$Chaque pattern est éditable directement en cliquant sur ses steps (cycle · → X → x). Le volet Mod donne accès à des transformations globales. Les changements de vitesse s'appliquent au prochain cycle pour rester en phase avec les autres couches.$$,
 $$[["◀ n ▶  Décalage","Tourne le pattern : déplace le point de départ sans changer les intervalles. Les appuis peuvent devenir des levés. Le Son 2:3 est un shift du Son 3:2."],["⇄  Intervertir","Échange les deux moitiés du pattern. Sur 8 steps : steps 1–4 ↔ 5–8."],["⇅  Inversion des accents","Échange forts et faibles : X ↔ x. Les silences restent inchangés."],["⊙  Rotation des accents","Fait tourner les niveaux d'un cran : · → x → X → ·."],["/2  ×2  T  Vitesse","Modifient la vitesse de la couche indépendamment des autres. /2 : step = noire (2× plus lent). ×2 : step = double croche (2× plus rapide). T (ternaire) : step = croche ternaire, vitesse ×3/2 — combiner /2+T donne la noire ternaire."],["🎲  Dé","Redistribue les steps au hasard (Fisher-Yates) en préservant les proportions exactes de X, x et · — même densité, même balance d'accents, ordre inédit."],["✨  Magie","Génère un nouveau pattern musicalement cohérent via deux phases : placement euclidien des sons forts (répartition régulière sur n steps) puis sons faibles déterminés par une chaîne de Markov (un son faible suit volontiers un son fort). L'intensité algorithmique varie aléatoirement. La vitesse de la couche peut aussi changer : 1 chance sur 3 de basculer en /2 ou ×2, avec 20 % de chance supplémentaire d'activer le mode T."]]$$::jsonb,
 'school', true),
('misc_familles',
 $$Les familles permettent de regrouper patterns, grooves et bands selon le style, la fonction musicale ou tout autre critère. Un même élément peut appartenir à plusieurs familles. Les familles de bands sont indépendantes des familles de patterns et grooves.$$,
 $$[["Filtrer","Dans les menus déroulants, sélectionner une famille pour n'afficher que les éléments concernés. Le filtre 'Tout' remet l'affichage complet."],["Perso","Le filtre 'Perso' affiche uniquement les éléments créés par l'utilisateur, indépendamment des familles."],["Créer / gérer","Le bouton ≡ de chaque section ouvre le panneau de gestion des familles : créer, renommer, supprimer, assigner aux éléments."],["Familles de bands","Les sons de batterie (bands) ont leurs propres familles, distinctes des familles de patterns et grooves. Exemples : Électro, Percussions, Rock, Minimaliste."]]$$::jsonb,
 'school', true),
('misc_metro',
 $$Le Métronome émet une pulsation de référence synchronisée avec le groove. Il peut être activé ou coupé à tout moment sans affecter le timing — seul le son est muté. Le volet Pulse permet de choisir quelles subdivisions sont audibles.$$,
 $$[["Métro ON / OFF","Active ou coupe le son du métronome. Le timing du groove continue dans tous les cas — 'OFF' signifie 'silencieux', pas 'arrêté'."],["Mesure","Un clic accentué (son différent) marque le premier temps de chaque mesure — le '1'. Permet de percevoir le début du cycle."],["Temps","Un clic sur chaque temps de la mesure selon la signature. En 4/4 : quatre clics par mesure. En 3/4 : trois clics."],["Subdiv","Subdivisions : clic sur chaque demi-temps. En 4/4 : 8 clics par mesure (croches). Utile pour les tempos lents ou pour ancrer les doubles croches."]]$$::jsonb,
 'school', true),
('misc_signature',
 $$La signature (ou chiffrage) de mesure définit la structure temporelle du groove : combien de temps par mesure, et quelle valeur de note constitue un temps. Elle s'affiche en fraction dans la barre Metro et conditionne le placement des séparateurs visuels dans la grille de steps.$$,
 $$[["Chiffre du haut — nombre de temps","Combien de temps il y a par mesure : 4/4 = 4 temps, 3/4 = 3 temps (valse), 5/4 = 5 temps (asymétrique), 6/8 = 2 temps."],["Chiffre du bas — valeur du temps","L'unité de temps. 4 = noire ♩ (2 steps), 8 = noire pointée ♩. (3 steps), 2 = blanche 𝅗𝅥 (4 steps). En 4/4, 1 temps = 2 cases à vitesse normale."],["Séparateurs visuels","Une ligne marque le début de chaque temps dans la grille. Leur espacement change selon la signature et le modificateur de vitesse de la couche (×2, /2, T)."],["Signatures composées — 6/8, 9/8, 12/8","Le temps est une noire pointée (3 croches). Feel naturellement ternaire. En 6/8 : 2 temps de 3 croches, séparateur toutes les 3 cases. Combinées avec T : séparateur toutes les ~4-5 cases."]]$$::jsonb,
 'school', true),
('misc_mesure',
 $$Une mesure (ou bar) est un groupe de temps délimité par deux barres de mesure. Le premier temps — le '1' — porte le poids rythmique le plus fort et déclenche l'accent du métronome. La notion de mesure est universelle en musique : c'est l'unité de répétition qui structure la durée.$$,
 $$[["En 4/4","4 temps par mesure, chaque temps = noire. La mesure la plus répandue dans la musique populaire mondiale. 1 mesure = 8 cases (steps) à vitesse normale."],["En 3/4","3 temps par mesure. Signature de la valse et de nombreuses musiques traditionnelles. 1 mesure = 6 cases à vitesse normale."],["En 6/8","6 croches regroupées en 2 temps de noire pointée. Feel ternaire — chaque temps 'cloche' en 3. 1 mesure = 6 cases à vitesse normale."],["Pattern et mesure","Un pattern de 8 cases couvre 1 mesure en 4/4 à vitesse normale. La durée réelle dépend du nombre de steps, de la signature et de la vitesse de la couche (/2, ×2, T)."]]$$::jsonb,
 'school', true),
('misc_step',
 $$Un step (pas) est l'unité de temps minimale de BoomTchak : la plus petite case dans la grille de pattern. En vitesse normale, 1 step = 1 croche (♪, 1/8 de ronde). C'est la résolution fondamentale du séquenceur, commune à toutes les couches.$$,
 $$[["Normal — croche ♪","1 step = 1/8. En 4/4 à 120 BPM : 1 step = 0,25 s. 2 steps = 1 temps (noire). 8 steps = 1 mesure."],["×2 — double croche ♬","1 step = 1/16. Chaque step est 2× plus court. La couche joue 2× plus vite à pattern identique."],["/2 — noire ♩","1 step = 1/4. Chaque step est 2× plus long. 1 step = 1 temps en 4/4."],["T — croche ternaire","1 step = 2/3 de croche (vitesse ×3/2). En 4/4 : 3 steps T = 1 temps. Produit un feeling de triolet ou de swing. Combiner /2+T pour la noire de triolet."],["Notations","X = son fort (100% vol), x = son faible (33% vol), · = silence. Cliquer une case fait cycler · → X → x → ·."]]$$::jsonb,
 'school', true)
on conflict (key) do update set
  chapo = excluded.chapo, bullets = excluded.bullets,
  scope = 'school', approved = true, updated_at = now();
-- Vérification
select 'familles' as table_name, count(*) from familles where scope='school'
union all select 'patterns', count(*) from patterns where scope='school'
union all select 'grooves',  count(*) from grooves  where scope='school'
union all select 'encyclo',  count(*) from encyclo  where scope='school';
